version: '3.8'
name: stagify

services:
  traefik:
    container_name: stagify-traefik
    image: traefik:latest
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  apache:
    container_name: stagify-apache
    image: php:apache
    command: ["sh", "-c", "a2enmod rewrite && mkdir -p /var/www/logs && chmod 777 /var/www/logs && apache2-foreground"]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.apache.rule=Host(`stagify.fr`)"
    volumes:
      - ./public:/var/www/html
      - ./src:/var/www/src
      - ./views:/var/www/views
      - ./vendor:/var/www/vendor
      - ./.env:/var/www/.env

  phpmyadmin:
    container_name: stagify-phpmyadmin
    image: phpmyadmin/phpmyadmin
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.rule=Host(`admin.stagify.fr`)"
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}

  mysql:
    container_name: stagify-mysql
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}