version: '3.8'
name: stagify

networks:
  stagify-network:
    driver: bridge

services:
  traefik:
    container_name: stagify-traefik
    image: traefik:latest
    command:
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - stagify-network

  apache:
    container_name: stagify-apache
    build:
      dockerfile: Dockerfile
    labels:
      - "traefik.http.routers.apache.rule=Host(`localhost`, `stagify.fr`)"
    volumes:
      - ./public:/var/www/html
      - ./assets:/var/www/html/assets
      - ./public/files:/var/www/html/files
      - ./src:/var/www/src
      - ./views:/var/www/views
      - ./.env:/var/www/.env
    networks:
      - stagify-network

  phpmyadmin:
    container_name: stagify-phpmyadmin
    image: phpmyadmin/phpmyadmin
    labels:
      - "traefik.http.routers.phpmyadmin.rule=Host(`admin.stagify.fr`)"
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}
    networks:
      - stagify-network

  mysql:
    container_name: stagify-mysql
    image: mysql:latest
    ports: #Expose the port for local development
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - stagify-network