version: '3.8'
name: stagify

networks:
  stagify-network:
    driver: bridge

services:
  traefik:
    container_name: stagify-traefik
    image: traefik:latest
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.stagify.acme.tlschallenge=true"
      - "--certificatesresolvers.stagify.acme.email=contact@stagify.fr"
      - "--certificatesresolvers.stagify.acme.storage=/certs/acme.json"
    ports:
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./certs:/certs
    networks:
      - stagify-network

  apache:
    container_name: stagify-apache
    build:
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.apache.rule=Host(`stagify.fr`)"
      - "traefik.http.routers.apache.entrypoints=websecure"
      - "traefik.http.routers.apache.tls.certresolver=stagify"
    volumes:
      - ./public:/var/www/html
      - ./assets:/var/www/html/assets
      - ./src:/var/www/src
      - ./views:/var/www/views
      - ./vendor:/var/www/vendor
      - ./certs:/var/www/certs
      - ./.env:/var/www/.env
    networks:
      - stagify-network

  phpmyadmin:
    container_name: stagify-phpmyadmin
    image: phpmyadmin/phpmyadmin
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.rule=Host(`admin.stagify.fr`)"
      - "traefik.http.routers.phpmyadmin.entrypoints=websecure"
      - "traefik.http.routers.phpmyadmin.tls.certresolver=stagify"
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}
    networks:
      - stagify-network

  mysql:
    container_name: stagify-mysql
    image: mysql:latest
    ports: #Expose the port for local development
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - stagify-network